name: Actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: actionlint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  actionlint:
    name: Actionlint
    permissions:
      contents: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/actionlint.yml@71f4345cad2998a16e8e14b800eee88c68d865ac # 0.2.3
