name: Actionlint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

concurrency:
  group: actionlint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  actionlint:
    name: Actionlint
    permissions:
      contents: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/actionlint.yml@bcb4d2812a8395a6c23925f562646e22784f6d2d # 0.11.1
