name: Dependency review

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
      pull-requests: write
    uses: NDDev-OpenNetwork/ci-workflows/.github/workflows/public-dependency-review.yml@1eaaa687f32f81c33ac99be3db0b76d0204420b8 # 0.1.8
