name: Dependency review

on:
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: dependency-review-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Dependency review
    permissions:
      contents: read
      pull-requests: write
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-dependency-review.yml@bcb4d2812a8395a6c23925f562646e22784f6d2d # 0.11.1
