name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "17 6 * * 3"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  scorecard:
    name: Scorecard
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-OpenNetwork/ci-workflows/.github/workflows/public-scorecard-json.yml@b4421b8660a7b6462095a9f492ea012b2a609abe # 0.1.17
    with:
      publish_results: false
