name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "17 6 * * 3"
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecard-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: Scorecard
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@bcb4d2812a8395a6c23925f562646e22784f6d2d # 0.11.1
    with:
      publish_results: false
