name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "17 6 * * 3"
  workflow_dispatch:

permissions: {}

concurrency:
  group: scorecard-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: Scorecard
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@ac4d1f469f5974741c7449305ffcbd5f05a5a47f # 0.5.1
    with:
      publish_results: false
