name: Secret scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "23 6 * * 3"
  workflow_dispatch:

permissions: {}

concurrency:
  group: secret-scan-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  secret-scan:
    name: Secret scan
    permissions:
      contents: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/secret-scan.yml@71f4345cad2998a16e8e14b800eee88c68d865ac # 0.2.3
